### ISSUE TITLE
Minor editorials

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/pracc-catalogue#14]
Section: "Statement of copyright" , last paragraph:
"coppresponding"?

Section 3, table 1, op-t68-001:
Double ..

Section 3, table 2, op-t68-017:
"...in the catalogue shall be identified" (shall is missing)

Section 3, table 2, op-t68-018:
Delete last sentence "This might be the same party as the catalogue provider."

**Comment by SiwMeckelborg** [comment]
Why delete last sentence in op-t68-018? 

Edit: sorry, looking closer into this I see the error, will be fixed
