### ISSUE TITLE
Section 5.1, table 6, BII3-T68-R002

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/pracc-catalogue#26]
Is the possible to restrict the allowed DocumentTypeCodes?

**Comment by SiwMeckelborg** [comment]
Should be discussed in WG meeting

**Comment by SiwMeckelborg** [comment]
Not to be restricted, but add more info om level in chapter 6.1

**Comment by SiwMeckelborg** [comment]
Solved in commit referenced in issue #25
