### ISSUE TITLE
Section 6.1, table 8

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/pracc-catalogue#27]
I think it would be a good idea to limit the codelists (marked in yellow) by restricting the lists. 
About the UOM recommendation, instead of adding a version,  maybe it could be specified, that the latest version should be supported to avoid that the receiver rejects a document due to unknown UOM codes?

**Comment by SiwMeckelborg** [comment]
To be discussed in WG meeting

**Comment by SiwMeckelborg** [comment]
@klakegg : Proposal for restriction of Mimecode
Siw to change guide

**Comment by klakegg** [comment]
My proposal:

Documents:
* application/pdf

Images:
* image/png
* image/jpeg
* image/tiff

Video:
* video/mp4
* video/x-msvideo
* video/x-ms-wmv

Drawings (selection from http://filext.com/file-extension/DWG):
* application/acad
* application/autocad_dwg
* application/dwg
* drawing/dwg
