### ISSUE TITLE
Add rules to ensure correct code for Procurement project identifier

### ISSUE THREAD

**Issue by SiwMeckelborg** [OpenPEPPOL/pracc-catalogue#29]
Add rule to verify that cac:ReferencedContract/cbc:ContractTypeCode exists, and has a value of 311.
This element has today a codelist rule CL-T68-R004, but this should be restricted so all instances refer to same documenttype to indicate the procurement project reference.

**Comment by klakegg** [comment]
Element cac:ReferencedContract is mandatory, but cbc:ContractTypeCode is optional. Are we making the latter mandatory too?

**Comment by SiwMeckelborg** [comment]
In my opinion, yes
