### ISSUE TITLE
op-t68-060

### ISSUE THREAD

**Issue by 3150jam** [OpenPEPPOL/pracc-catalogue#34]
It should be possible to specify a manufacturing date, a best before date and an expiry date (last date when product may be used or consumed) for an item.
Use case 1:
In pre-award catalogue request the contracting authority (CA) ask for a certain vaccine to be offered. Because this vaccine is defined as perishable goods the CA ask in the tender economic operator (EO) to specify best before date and expiry date.  The fields will guide CA in planning the vaccine program regarding logistic to the country that it will be used and when to ordering the vaccine in good time.  The information will also be used in the electronic catalogue if the EO must update information.
Use case 2:
Contracting authority (CA) ask for a shipment of meat.  CA will produce meals for resident in a nursing home.  To give food and beverage manger best possible information in planning all the meals he must know which shipment he will use when.

**Comment by SiwMeckelborg** [comment]
I am a bit uncertain what you mean here, should the requirement include the use case description? Or do you intend to create more descriptions in the exisiting use cases and refer to these?

**Comment by 3150jam** [comment]
I beleive you can use the text in case description with an xml example

**Comment by 3150jam** [comment]
I belive we agreed in previus meeting that you incudes this use case in chapter 7
