### ISSUE TITLE
op-t68-061

### ISSUE THREAD

**Issue by 3150jam** [OpenPEPPOL/pracc-catalogue#35]
It should be possible to specify serial numbers, batch numbers and lot numbers for an item.
Use case 1:
The procurement office in the air force has bought vital part to their helicopters. They have a system to log all spear parts. To be able to link specifications in the order to specific serial numbers, batch numbers and lot numbers for the item bought they need the information in the catalogue received from EO.  
The information can be used in repetitive orders referring to the information used in the pre-award catalogue or in catalogue or used as reference to the EO in improvement of the quality of the product.  If an accident happens CA can trace the product down to the specific production batch.

**Comment by SiwMeckelborg** [comment]
See my comment on issue #34 Same is valid here

**Comment by 3150jam** [comment]
See my comment in #34

**Comment by 3150jam** [comment]
I belive we agreed in previus meeting that you incudes this use case in chapter 7

**Comment by SiwMeckelborg** [comment]
Serial ID and batch numbers are not part of BII PreAward catalogue. I suggest to remove this requirement from the PEPPOL BIS
