### ISSUE TITLE
Regarding issue 03 in the minutes 30.08.2017

### ISSUE THREAD

**Issue by 3150jam** [OpenPEPPOL/pracc-catalogue#36]
Evaluate text in use case 4.2 and 4.3 and see if similarities are appropriate:

The text is almost identical so my recomandation is ti remove https://test-vefa.difi.no/peppolbis/pracc/catalogue/#_use_case_1 and keep https://test-vefa.difi.no/peppolbis/pracc/catalogue/#_use_case_2 and rename it Use Case 1

**Comment by SiwMeckelborg** [comment]
This issue is a proposed solution to issue #23.
