### ISSUE TITLE
Reference to the corresponding Call for tenders

### ISSUE THREAD

**Issue by ThomasSFTI** [OpenPEPPOL/pracc-catalogue#44]
The CEN/BII pre award catalogue states:
“A pre-award catalogue line must contain information on the offered item and a reference to the corresponding Call for tenders requested deliverable.”

But there is no such reference in this document and maybe not in the message.

**Add** Reference to the corresponding Call for tenders to the PreAward Catalogue.

**Comment by SiwMeckelborg** [comment]
It is present in the detailed message table, that is found in Appendix B
