### ISSUE TITLE
Include 5 words in existing text based on directiv

### ISSUE THREAD

**Issue by 3150jam** [OpenPEPPOL/pracc-catalogue#49]
https://test-vefa.difi.no/peppolbis/pracc/catalogue/1.0/bis/#_environment_social_responsibility_and_ecological

"and other means of proof"

Public actors will have requirements related to the environment, ecologically produced food and fair trade. They will also demand that basic
human rights are respected in the product production and trade. To be able to highlight products that meet some of these criteria, 
the PEPPOL BIS pre-award catalogue contains elements to document Environmental labelling and Social certificates **and other means of proof.** 
The labels are connected to the relevant product or service on line level enabling the buyer to evaluate them in the tendering tool. 
Detailed information about the different labels can be found on the issuing party’s web-site which is referred to via an URI.

**Comment by SiwMeckelborg** [comment]
Add text "and other means of proof" as suggested in text above.
