### ISSUE TITLE
Remove reference to BII3 according to statement text

### ISSUE THREAD

**Issue by 3150jam** [OpenPEPPOL/pracc-catalogue#8]
I suggest removing the number 3 of BII3 do to harmonize the text according to statement text

[https://test-vefa.difi.no/peppolbis/pracc/catalogue/#principles](url)

**Comment by SiwMeckelborg** [comment]
I disagree, as the statement is a general copyright text used by all PEPPOL BIS'es, and then each BIS further specifies exactly which specifications this document is based on. If you look into existing BIS document, they specify BII 2 in the text, example from ordering: "This PEPPOL BIS is based on
the CEN WS/BII2 Profile “BII Profile 28 Ordering”."

**Comment by 3150jam** [comment]
Then we can refere to BII2 that also had a deliverable for pre-award catalogue[http://www.cenbii.eu/deliverables/cen-bii-2/cwa-16560-etendering/](url)

**Comment by SiwMeckelborg** [comment]
As we are using BII3 as the base for this work, we need to reference BII3
